# Generated by Django 5.0.6 on 2024-05-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('cat', 'кіт'), ('dog', 'пес'), ('mouse', 'пацюк')], default='cat', max_length=10, verbose_name='Вид'),
        ),
        migrations.AlterModelTable(
            name='pet',
            table='pet',
        ),
    ]
